#!/usr/bin/env php
<?php

if (isset($GLOBALS['_composer_autoload_path'])) {
    require_once $GLOBALS['_composer_autoload_path'];

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require_once $file;

            break;
        }
    }

    unset($file);
}

$application = new Symfony\Component\Console\Application();

$application->add(new Setuphp\Command\SetuphpCommand());
$application->add(new Setuphp\Command\GitCommand());
$application->setDefaultCommand('setuphp');

$application->run();
